# Generated by Django 4.2.22 on 2025-06-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='weatheroverride',
            constraint=models.UniqueConstraint(fields=('city', 'date'), name='unique_city_date'),
        ),
    ]
